### ISSUE TITLE
Assigning a permission set to a account does not work for new accounts

### ISSUE THREAD

**Issue by Robertjan123** [schubergphilis/awsssolib#5]
For new accounts it is not possible to assign a permission set to a new account. First an application instance for AWS account  needs to be provisioned and then a IAM Identity provider needs to be provisioned in the target account, but for the latter it is not clear how to automate this.

**Comment by SayantanKhanra10** [comment]
@Robertjan123 You can use the method **associate_group_to_account** to assign a group to an account. 

you need to pass the group_name, account_name and the permission_set_name

Let me know if you need more info

**Comment by Robertjan123** [comment]
I was getting the following error: 
[ERROR] ValueError: {     "__type": "com.amazon.coral.validate#ValidationException",     "message": "1 validation error detected: Value '' at 'instanceId' failed to satisfy constraint: Member must have length greater than or equal to 1" }Traceback (most recent call last):  File "/var/task/update-sso.py", line 52, in lambda_handler    sso_connection.associate_group_to_account(group_name, account['account_name'], role+'-'+account['stage'])  File "/var/task/awsssolib/awsssolib.py", line 390, in associate_group_to_account    profile_id = self._provision_application_profile_for_aws_account_instance(permission_set_name, account_name)  File "/var/task/awsssolib/awsssolib.py", line 361, in _provision_application_profile_for_aws_account_instance    raise ValueError(response.text)
--

The instance_id could not be retrieved, because there was no application instance for the AWS new account. This could be created with the API call sso:ProvisionApplicationInstanceForAWSAccount. But it was still not working because the SAML identity provider was not provisioned yet in the target account, and this could be solved by calling the sso:ProvisionSAMLProvider.
However it all seems irrelevant now that AWS has released the official APIs and we can use boto3 for python: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-admin.html

**Comment by SayantanKhanra10** [comment]
Yes Indeed. sso-admin can be utilized for most of the admin activities. But still there are few things which are not supported by Boto.
